### Variables ###
NAME = libftprintf.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
FILES = ft_printf.c ft_putchar.c ft_putstr.c ft_putnbr ft_unsint.c
OBJS = $(FILES:.c=.o) # generates the same FILES list whith the .o extension
